Added ReqestIP to Apollo backend
oslabs-beta/GraphQL-Gateway pull request #106
Opened 2022-08-05 00:35 UTC by donjewey

2022-08-05 02:47 UTC, shalarewicz requested changes
Small change

2022-08-05 02:47 UTC, shalarewicz commented on server/index.ts
> +            res.status(500).send(new Error(`Project not found: ${err}`))
This should be a 404 error

2022-08-05 04:02 UTC, shalarewicz approved these changes

2022-08-06 15:47 UTC, evanmcneely approved these changes

2022-08-06 17:26 UTC, merged