TS, Webpack, and development environment setup complete
oslabs-beta/GraphQL-Gateway pull request #6
Opened 2022-05-17 04:24 UTC by donjewey

Integrated webpack, typescript, husky, prettier, and eslint into the project, as well as all of the necessary scripts into `package.json`

2022-05-17 04:46 UTC, donjewey commented
#1 Issue completed, except for file structure. Need to merge with backend integration PR to complete outlying file structure.

2022-05-17 05:00 UTC, milos381 approved these changes

2022-05-17 10:48 UTC, evanmcneely requested changes
1. Add these properties to the tsconfig file: "strictNullChecks" true and "noImplicitAny" true

2022-05-17 13:56 UTC, shalarewicz requested changes

2022-05-18 01:15 UTC, donjewey commented on package.json
> +        "webpack": "^5.72.1",
Done!

2022-05-18 02:21 UTC, evanmcneely approved these changes
We may still have to configure prettier and eslint after this but we can do that separately.

2022-05-18 14:26 UTC, shalarewicz approved these changes

2022-05-18 21:54 UTC, merged